#!/usr/bin/env python3
"""Find every Forth primitive in the image and write them out as tracer
entry points.

## Why this exists

`disasm.py` follows 6502 control flow from the reset vector. Point it at
Karateka and it reaches **0.7% of the ROM** -- 323 bytes, 173 instructions
-- and stops, because after boot the machine stops executing 6502 and
starts executing a thread. Everything else is entered by `NEXT` computing
an address out of a table, which no static tracer can follow.

But the primitives themselves are ordinary 6502, and they are trivially
findable. A primitive's code field holds a pointer to its own code, two
bytes on: `$936C` contains `$936E`. That self-reference is the whole
signature, and nothing else in the image looks like it.

Hand those 200 addresses to the tracer as entries and coverage goes from
0.7% to **18.3%** -- 8977 bytes, 4407 instructions. That is the executable
half of the image; the rest is threaded data, which is what it should be.

    python patches/karateka-entries.py
    python tools/disasm.py karateka.a78 -c patches/karateka-entries.json \\
           --check-gaps -o src

## What the gap check then says

With the primitives loaded, `--check-gaps` reports that **no traced code
enters any gap**: all 1021 apparent `JSR`/`JMP` targets in unexplained
territory are byte coincidences, the `$20`/`$4C`/`$6C` falling inside
threaded data rather than starting an instruction. That is the structural
claim about this image -- that it is entered only through the thread --
checked rather than assumed.

It also names six small ranges a traced `JMP` steps over, which are the
places worth decoding by hand:

    $4004-$400D (10)   skipped by $4001 JMP $405F
    $4040-$4041 (2)    skipped by $403D JMP $4042
    $4054-$4055 (2)    skipped by $4051 JMP $4056
    $4D1D-$4D1F (3)    skipped by $4D1A JMP $4D76
    $5011-$501D (13)   skipped by $500E JMP $501E

Contains no cartridge data: addresses only, computed from your own dump.
"""
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import karateka  # noqa: E402

SPACE = "rom"           # the space disasm.py names for an unbanked 48K image


def primitives(rom, base=0x4000):
    """Every address whose two bytes point at the address two bytes on."""
    out = []
    for addr in range(base, base + len(rom) - 2, 2):
        o = addr - base
        if (rom[o] | (rom[o + 1] << 8)) == addr + 2:
            out.append(addr + 2)
    return out


def main():
    _src, _hdr, rom = karateka.load_source()
    entries = primitives(rom)
    out = os.path.join(HERE, "karateka-entries.json")
    io.open(out, "w", encoding="utf-8").write(json.dumps({
        "_README": "Tracer entry points for Karateka (NTSC), generated by "
                   "karateka-entries.py. Every Forth primitive's code "
                   "address, found by its code field pointing at itself. "
                   "Addresses only -- no cartridge data.",
        "entries": ["%s:0x%04X" % (SPACE, e) for e in entries],
    }, indent=2) + "\n")
    print("%d primitives -> %s" % (len(entries), os.path.basename(out)))
    print("  python tools/disasm.py <rom> -c %s --check-gaps -o src"
          % os.path.relpath(out, os.path.dirname(HERE)))


if __name__ == "__main__":
    main()
